name: Deploy via FTP

# Configuração de deploy com credenciais atualizadas
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer:v2
        coverage: none

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Dependencies
      run: |
        composer install --no-dev --prefer-dist --no-progress --optimize-autoloader
        composer dump-autoload --optimize
    - name: Setup Production Environment
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      run: |
        echo "DB_HOST=127.0.0.1" > .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=u492226363_school" >> .env
        echo "DB_USERNAME=u492226363_admin" >> .env
        echo "DB_PASSWORD=$DB_PASSWORD" >> .env
        echo "JWT_SECRET=$JWT_SECRET" >> .env
        echo "CORS_ALLOW_ORIGIN=https://seoeads.com" >> .env
    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 62.72.62.253
        username: u492226363.deploy
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /api/
        protocol: ftp
        port: 21
        security: loose
        dangerous-clean-slate: false
        log-level: verbose
        timeout: 60000
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/tests/**
          README.md
          .env.example
          .env.production
          phpunit.xml 